# Use admin/admin as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: svinjice-mongoDB2
    environment:
      MONGO_INITDB_DATABASE: svinjgojac
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
